import os
import exifread

def detect_ai_signature(tags: dict) -> tuple[bool, list[str]]:
    """
    EXIF etiketlerini analiz ederek bilinen AI (Yapay Zeka) araçlarının yazılım izlerini tespit eder.
    
    Args:
        tags (dict): Görselden çıkarılan EXIF etiketlerini içeren sözlük.
        
    Returns:
        tuple[bool, list[str]]: Şüpheli bir iz bulunup bulunmadığını (True/False) ve 
                                bulunan izlerin detaylarını içeren bir liste döner.
    """
    ai_keywords = [
        # Popüler AI Görüntü Üreticileri ve Modeller (A-Z)
        "adobe firefly", "animegenius", "artbreeder", "astria", "automatic1111", 
        "bing image creator", "canva magic", "civitai", "clipdrop", "comfyui", 
        "craiyon", "dall-e", "dalle", "deepbrain", "deepdream", "deepfloyd", 
        "deforum", "dezgo", "dream by wombo", "dreamlike", "dreamstudio", 
        "ebsynth", "flux", "fooocus", "fotor ai", "gencraft", "gemini", 
        "getimg", "grok", "haiper", "heygen", "hotpot", "huggingface", 
        "ideogram", "imagen", "imagine with meta", "invokeai", "jasper art", 
        "kaiber", "kakarot", "kandinsky", "kling ai", "krea", "leonardo", 
        "let's enhance", "lexica", "luma ai", "mage.space", "magnific", 
        "maze.guru", "meta ai", "midjourney", "midjourney bot", "muse", 
        "neural.love", "nightcafe", "novelai", "openai", "openart", "parti", 
        "photoroom", "phygital", "pika", "pixai", "playgroundai", "prompthero", 
        "recraft", "remini", "replicate", "rudalle", "runway", "scenario", 
        "sd-webui", "sdxl", "seaart", "sinkin", "sora", "stable diffusion", 
        "stable video diffusion", "starryai", "stablediffusion", "synthesia", 
        "tensor.art", "topaz gigapixel", "topaz labs", "upscayl", "vanceai", 
        "vqgan", "wombo", "wuerstchen", "yodayo",
        
        # Jenerik AI ve Makine Öğrenimi Terimleri
        "ai art", "ai generated", "ai-generated", "artificial intelligence", 
        "created with ai", "deep learning", "diffusion model", 
        "generated by ai", "generative adversarial network", "generative ai", 
        "generative fill", "img2img", "machine learning", "neural network", 
        "synthetic media", "synthography", "text-to-image", "txt2img",
        
        # Üretim Parametreleri ve Alt Teknikler (Stable Diffusion, ComfyUI vb.)
        "a1111", "animate-diff", "cfg scale:", "clip skip:", "control module:", 
        "controlnet", "denoising strength:", "dreambooth", "face restoration:", 
        "hires steps:", "hires upscaler:", "hypernetwork", "lora:", 
        "model hash:", "negative prompt:", "prompt:", "sampler:", "seed:", 
        "steps:", "textual inversion", "vae:"
    ]
    
    critical_tags = [
        # Standart ve en çok kullanılan EXIF etiketleri
        "Image Software", "Image CreatorTool", "EXIF UserComment", 
        "Image ImageDescription", "Image Make", "Image Model",
        "Software", "CreatorTool", "UserComment", "ImageDescription", "Make", "Model",
        
        # Genişletilmiş etiketler (Farklı cihaz ve yazılımların kullanabileceği alanlar)
        "Image ProcessingSoftware", "Image Artist", "Image Copyright", 
        "Image DocumentName", "Image HostComputer", "Image ApplicationNotes",
        "EXIF MakerNote", "EXIF ImageUniqueID", "EXIF CameraOwnerName",
        "Image XPTitle", "Image XPComment", "Image XPAuthor", "Image XPSubject",
        
        # XMP, IPTC ve ExifRead'in yakalayabileceği diğer özel alanlar
        "Image PrintIM", "Image Rating", "Image History"
    ]
    
    found_signatures = []
    
    for tag_name in critical_tags:
        if tag_name in tags:
            tag_value = str(tags[tag_name]).lower()
            for keyword in ai_keywords:
                if keyword in tag_value:
                    found_signatures.append(
                        f"Şüpheli iz '{keyword}', şu etikette bulundu: '{tag_name}' -> {tags[tag_name]}"
                    )
                    
    return len(found_signatures) > 0, found_signatures

def analyze_metadata(file_path: str) -> dict:
    """
    Belirtilen görsel dosyasının EXIF/Metadata'sını çıkarır, AI yazılım izlerini arar 
    ve sonucu ekrana okunabilir (human-readable) formatta yazdırır.
    
    Args:
        file_path (str): İncelenecek görselin dosya yolu.
        
    Returns:
        dict: Çıkarılan tüm EXIF etiketlerini içeren sözlük. Hata durumunda veya veri bulunmazsa boş sözlük döner.
    """
    if not os.path.exists(file_path):
        print(f"Hata: İncelenecek dosya bulunamadı -> {file_path}")
        return {}
        
    # Gereksinim 1 & 2: Format doğrulama kontrolü (.jpg, .jpeg, .png)
    valid_extensions = {".jpg", ".jpeg", ".png"}
    _, ext = os.path.splitext(file_path)
    if ext.lower() not in valid_extensions:
        print(f"Hata: Desteklenmeyen dosya formatı ({ext}). Sistem sadece .jpg, .jpeg ve .png formatlarını kabul etmektedir. Analiz durduruldu.")
        return {}
        
    tags = {}
    try:
        # Görsel, gereksinimlerde belirtildiği üzere ikili (binary) modda (rb) okunuyor
        with open(file_path, 'rb') as image_file:
            tags = exifread.process_file(image_file)
            
        if not tags:
            print("Uyarı: Metadata bulunamadı (EXIF verisi temizlenmiş olabilir veya desteklenmeyen format).")
            return {}
            
        print(f"\n--- Metadata Analiz Raporu: {file_path} ---")
        print(f"Toplam {len(tags)} EXIF etiketi başarıyla çıkarıldı.")
        
        # AI yazılım izi kontrolü yapılıyor
        is_ai, signatures = detect_ai_signature(tags)
        
        if is_ai:
            print("\n[!] Şüpheli Yazılım İzi Bulundu [!]")
            for sig in signatures:
                print(f" - {sig}")
            print("-" * 45)
        else:
            print("\n[+] Temiz: Bilinen bir AI aracı izine rastlanmadı.")
            
        # Temiz ve okunabilir bir çıktı (Clean Output) için bazı önemli etiketleri özetleyelim
        print("\nÖnemli Metadata Detayları:")
        important_tags = [
            "Image Make", "Image Model", "Image Software", 
            "Image DateTime", "EXIF ExifImageWidth", "EXIF ExifImageLength"
        ]
        
        for tag in important_tags:
            if tag in tags:
                print(f"{tag:<25}: {tags[tag]}")
                
        print("-------------------------------------------\n")
        return tags
        
    except Exception as e:
        print(f"Hata: Dosya işlenirken beklenmeyen bir sorun oluştu: {e}")
        return {}

if __name__ == "__main__":
    import os
    import csv
    
    current_dir = os.path.dirname(os.path.abspath(__file__))
    base_dir = os.path.dirname(current_dir) 
    raw_dir = os.path.join(base_dir, "data", "raw")
    report_path = os.path.join(base_dir, "data", "metadata_test_raporu.csv")
    
    print(f"--- Toplu Analiz Başlatılıyor: {raw_dir} ---")
    
    if not os.path.exists(raw_dir):
        os.makedirs(raw_dir)
        print(f"Uyarı: {raw_dir} klasörü yoktu, oluşturuldu.")
        
    valid_exts = (".jpg", ".jpeg", ".png", ".tiff")
    image_files = [f for f in os.listdir(raw_dir) if f.lower().endswith(valid_exts)]
    
    if not image_files:
        print("Klasörde analiz edilecek fotoğraf bulunamadı. Lütfen data/raw klasörüne fotoğraf ekleyin.")
    else:
        with open(report_path, mode="w", newline="", encoding="utf-8") as file:
            writer = csv.writer(file)
            writer.writerow(["Dosya Adi", "AI Izi Bulundu Mu?", "Bulunan Izler", "Kullanilan Yazilim (Software)"])
            
            for img_name in image_files:
                img_path = os.path.join(raw_dir, img_name)
                print(f"\n{'='*40}\nİnceleniyor: {img_name}...")
                
                tags = analyze_metadata(img_path)
                
                if tags:
                    is_ai, signatures = detect_ai_signature(tags)
                    sig_text = " | ".join(signatures) if is_ai else "Temiz (Izi Yok)"
                    software = str(tags.get("Image Software", "Bilinmiyor"))
                else:
                    is_ai, sig_text, software = False, "EXIF Verisi Yok", "Bilinmiyor"
                
                writer.writerow([img_name, "Evet" if is_ai else "Hayir", sig_text, software])
        
        print(f"\n[Başarılı] Tüm testler tamamlandı!")
        print(f"[Rapor Kaydedildi] Sonuçları Excel'de açmak için: {report_path}")